### ISSUE TITLE
Bug in global navigation

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/TeachingRobotics#119]
In global_navigation practice, I've tried to get robot orientation using self.sensor.getRobotTheta(). When I run the practice it gives an error. It seems that Pose3D doesn't have the yaw attribute. The error is: 

<pre>
Exception in thread Thread-2: 
Traceback (most recent call last): 
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner 
    self.run() 
  File "/home/vanejessi/Escritorio/Vanessa/TeachingRobotics/src/global_navigation/MyAlgorithm.py", line 36, in run 
    self.execute() 
  File "/home/vanejessi/Escritorio/Vanessa/TeachingRobotics/src/global_navigation/MyAlgorithm.py", line 267, in execute 
    orientationRobot = self.sensor.getRobotTheta() 
  File "/home/vanejessi/Escritorio/Vanessa/TeachingRobotics/src/global_navigation/sensors/sensor.py", line 78, in getRobotTheta 
    return self.pose3d.Yaw() 
AttributeError: 'Pose3D' object has no attribute 'Yaw' 
</pre>

[source](http://jderobot-developer-list.2315034.n4.nabble.com/Problem-with-Global-navigation-practice-td4643244.html)

**Comment by aitormf** [comment]
merged #120
